spring:
  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:44200/sample?useCursorFetch=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      connectionTimeout: 2000
      maximumPoolSize: 20
      userName: dbuser
      password:
  jpa:
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 1000
      hibernate.jdbc.time_zone: UTC
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  redis:
    host: 127.0.0.1
    port: 44201
#    password:
#    ssl:
#    timeout:
#    cluster:
#      nodes:
#    sentinel:
#      master:

# for binding parameter logging
logging.level.org.hibernate.type.descriptor.sql: trace
