version: "3"

networks:
  network:

services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: sample-mysql
    networks:
      - network
    ports:
      - 44200:3306
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=abcd1234
      - MYSQL_ROOT_PASSWORD=sample
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:5-alpine
    container_name: sample-redis
    networks:
      - network
    ports:
      - 44201:6379
    volumes:
      - ./redis/data:/data
